/*
** Created by Christian Howard on 10/27/22.
*/
#ifndef TENTPITCH_SDG_SRC_MESHING_MESH_ABSTRACTIONS_STRATIFIED_MESH_FWD_H_
#define TENTPITCH_SDG_SRC_MESHING_MESH_ABSTRACTIONS_STRATIFIED_MESH_FWD_H_

namespace tp_sdg::meshing::abstractions {
class StratifiedMesh;
}

#endif //TENTPITCH_SDG_SRC_MESHING_MESH_ABSTRACTIONS_STRATIFIED_MESH_FWD_H_
