/*
** Created by Christian Howard on 10/15/22.
*/
#ifndef TENTPITCH_SDG_SRC_SIMULATION_THREADED_THREADED_SIMULATION_H_
#define TENTPITCH_SDG_SRC_SIMULATION_THREADED_THREADED_SIMULATION_H_

namespace tp_sdg::simulation::threaded {
int dummy_func(int a);
}

#endif //TENTPITCH_SDG_SRC_SIMULATION_THREADED_THREADED_SIMULATION_H_
